version: '3.8'

services:
  main-service:
    build: ./main_service
    ports:
      - "5001:5001"
    volumes:
      - ./main_service:/app/main_service

  security-service:
    build: ./security_service
    ports:
      - "5002:5002"
    volumes:
      - ./security_service:/app/security_service

  friends-service:
    build: ./friends_service
    ports:
      - "5003:5003"
    volumes:
      - ./friends_service:/app/friends_service

  item-service:
    build: ./item_service
    ports:
      - "5004:5004"
    volumes:
      - ./item_service:/app/item_service


